return {
  "nguyenvukhang/nvim-toggler",
  keys = { { "<Leader><Leader>", '<cmd> lua require("nvim-toggler").toggle() <cr>' } },
  config = function()
    require("nvim-toggler").setup({
      inverses = {
        ["==="] = "!==",
        ["=="] = "!=",
        ["min"] = "max",
        ["Min"] = "Max",
        ["MIN"] = "MAX",
        ["yes"] = "no",
        ["Yes"] = "No",
        ["on"] = "off",
        ["On"] = "Off",
        ["up"] = "down",
        ["Up"] = "Down",
        ["top"] = "bottom",
        ["Top"] = "Bottom",
        ["left"] = "right",
        ["Left"] = "Right",
        ["1"] = "0",
        ["true"] = "false",
        ["True"] = "False",
        ["stringify"] = "parse",
        ["mouseup"] = "mousedown",
        ["mouseover"] = "mouseout",
        ["keyup"] = "keydown",
        ["add"] = "remove",
        ["before"] = "after",
        ["Before"] = "After",
        ["Relative"] = "Absolute",
        ["relative"] = "absolute",
        ["horizontal"] = "vertical",
        ["Horizontal"] = "Vertical",
        [">"] = "<",
        ["}"] = "{",
        ["]"] = "[",
        [")"] = "(",
        ["+"] = "-",
        ["\\"] = "/",
      },
      remove_default_keybinds = true,
      remove_default_inverses = true,
    })
  end,
}
